lint: add no-misused promises to linter
across-protocol/relayer pull request #1581
Opened 2024-05-31 15:15 UTC by bmzig

The `no-misused-promises` rule enforces unresolved promises to be resolved before used (e.g. in a boolean conditional or in an object). Adding this in the linter will ideally prevent bugs which occur due to handling promises instead of the resolved value.

2024-05-31 17:15 UTC, james-a-morris requested changes
I think some of these would impact dataworker timings

2024-05-31 17:15 UTC, james-a-morris commented on src/dataworker/Dataworker.ts
> +    if (!(await this.rootCache[key]) || process.env.DATAWORKER_DISABLE_REBALANCE_ROOT_CACHE === "true") {
This is meant to be unawaited - we're testing for the existence of the promise

2024-05-31 19:21 UTC, bmzig commented on src/dataworker/Dataworker.ts
> +    if (!(await this.rootCache[key]) || process.env.DATAWORKER_DISABLE_REBALANCE_ROOT_CACHE === "true") {
Is this true for the other changes? This one is fixed here: https://github.com/across-protocol/relayer-v3/pull/1581/commits/f67cd4156a12f8943643d21025bfd481bd9eb022

2024-06-05 10:57 UTC, bmzig commented on src/dataworker/Dataworker.ts
> +    if (!(await this.rootCache[key]) || process.env.DATAWORKER_DISABLE_REBALANCE_ROOT_CACHE === "true") {
Also fixed here: https://github.com/across-protocol/relayer/pull/1581/commits/b6826bfaa25c5027460cf1dd3d65a2ecbb4146d1

2024-06-05 11:36 UTC, nicholaspai approved these changes

2024-06-05 11:36 UTC, nicholaspai commented
> I think some of these would impact dataworker timings

Agreed. Sometimes we purposefully don't await promises. We cache the unresolved promise so the promises can execute in the background

2024-06-05 12:15 UTC, james-a-morris approved these changes

2024-06-05 12:15 UTC, james-a-morris commented on .eslintrc.js
> +    // "require-await": "error",
If this is wrong we can remove it

2024-06-05 12:21 UTC, bmzig commented on .eslintrc.js
> +    // "require-await": "error",
https://github.com/across-protocol/relayer/pull/1581/commits/40a8061d238182a95e35a0cfb09af8486ee28ac5

2024-06-05 14:40 UTC, merged