chore(v20): bump to v20
across-protocol/relayer pull request #1599
Opened 2024-06-07 11:16 UTC by james-a-morris

I've seen a roughly 20% speed improvement

2024-06-07 11:17 UTC, nicholaspai commented
> I've seen a roughly 20% speed improvement

should we also bump this in the sdk/contracts?

2024-06-07 11:17 UTC, nicholaspai approved these changes

2024-06-07 11:28 UTC, bmzig approved these changes

2024-06-07 20:38 UTC, nicholaspai requested changes
do we need to change the `engine` in package.json?

2024-06-09 14:13 UTC, james-a-morris commented
> do we need to change the `engine` in package.json?

This specifies that the Node version to run this executable should be greater than `>=16.18.0`, or it will throw if we try to run it. Technically, we can run the bots in v16, so it wouldn't need to be changed. I'm going to bump it because we want third party relayers to use v20 moving forward

2024-06-10 17:21 UTC, nicholaspai approved these changes

2024-06-10 17:45 UTC, merged