feat(lite chain): force origin chain repayment
across-protocol/relayer pull request #1629
Opened 2024-06-18 20:45 UTC by james-a-morris

This PR is blocked by https://github.com/across-protocol/sdk/pull/662

The goal of this PR is to make sure fills made by the relayer are made with the origin chain id. Since the same line of code was highly correlated, the removal of slow fills for lite chains has also been added.

There is one outstanding piece of information needed, which I am resolving offline. Therefore, I will keep this as WiP

2024-06-19 08:48 UTC, pxrl commented on src/relayer/Relayer.ts
> +        this.fillRelay(deposit, isLiteChain ? originChainId : repaymentChainId, realizedLpFeePct, gasLimit);
I think this belongs moreso in `relayer.resolveRepaymentChain()` - it shouldn't be necessary to add it here :+1:

2024-06-19 08:49 UTC, pxrl commented on src/relayer/Relayer.ts
>      } else if (selfRelay) {
This code is almost never used, so I'd prefer to keep it really small by just updating the existing logic as follows:

```suggestion
    } else if (selfRelay && !isLiteChain) {
```

2024-06-19 08:50 UTC, pxrl commented on src/relayer/Relayer.ts
> +          isLiteChain,
This is implied by the log message itself.

```suggestion
```

2024-06-19 08:52 UTC, pxrl commented on src/relayer/Relayer.ts
> +        });
Thoughts on relocating this into `Relayer.requestSlowFill()` ? Otherwise this "main" relayer function ends up quite long and filled with lots of verbose log messages.

2024-06-19 14:23 UTC, nicholaspai commented on src/clients/InventoryClient.ts
> +    if (this.hubPoolClient.configStoreClient.isChainLiteChainAtBlock(originChainId)) {
I'm not sure this belongs in here. @pxrl wdyt? should the lite chain decision be in here or in the relayer? Also james I see you're not apassing in the deposit.quoteTimestamp which is going to be necessary to determine if the deposit origin chain was a lite chain at deposit time

2024-06-19 14:23 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +        this.fillRelay(deposit, isLiteChain ? originChainId : repaymentChainId, realizedLpFeePct, gasLimit);
I agree with paul

2024-06-21 13:32 UTC, james-a-morris commented on src/relayer/Relayer.ts
>      } else if (selfRelay) {
Good call. I kept the internal conditional just because then we'd have to add an else-if to the else statement below.

2024-06-21 13:32 UTC, james-a-morris commented on src/relayer/Relayer.ts
> +        this.fillRelay(deposit, isLiteChain ? originChainId : repaymentChainId, realizedLpFeePct, gasLimit);
Good call

2024-06-21 13:32 UTC, james-a-morris commented on src/clients/InventoryClient.ts
> +    if (this.hubPoolClient.configStoreClient.isChainLiteChainAtBlock(originChainId)) {
I'd prefer to keep this here because we want to lock repayment chain possibilities of lite chains to the origin. THis function is used by the relayer's repayment chain id function to determine which possible chains to reason about.

2024-06-24 14:15 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +      this.logger.warn({
```suggestion
      this.logger[this.config.sendingRelaysEnabled ? "warn" : "debug"]({
```

2024-06-24 14:15 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +      this.logger.warn({
we should try to reduce noise in the rebalancer when these deposits happen

2024-06-24 14:17 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +        return;
@pxrl isn't this going to be an issue if we ever send a self deposit? We'll never fill it meaning funds will be stuck forever? Why can't we fill these and then get repaid on the origin chain?

2024-06-24 14:21 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +                // We need to ensure that the repayment chain is the origin chain if the deposit originates
This change isn't sufficient, as there are several other places where we populate the `bundleFillsV3` object. 

The important object we need to modify is `bundleFillsV3`, which should only be modified in this file by `updateBundleFillsV3()`. Therefore if you search for this function, you'll see that repayment chain ID for a successful fill is only computed by `getRefundInformationFromFill()` but please double check me on this

2024-06-24 14:21 UTC, nicholaspai requested changes
The dataworker changes won't work yet and needs some tests, but the relayer looks good though still probably needs tests

2024-06-24 15:29 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +                v3RelayHashes[this.getRelayHashFromEvent(fill)].deposit.originatesFromLiteChain
what if `deposit.originatesFromLiteChain` isn't defined?

2024-06-24 15:36 UTC, james-a-morris commented on src/clients/BundleDataClient.ts
> +                v3RelayHashes[this.getRelayHashFromEvent(fill)].deposit.originatesFromLiteChain
These are loops over validated fills that require a deposit to be defined. However, we can change it to be something like: https://github.com/across-protocol/relayer/pull/1629/commits/2db63b8bd2fbb96216731a2066913aaf0a5ded17

2024-06-24 19:06 UTC, james-a-morris commented on src/clients/BundleDataClient.ts
> +                // We need to ensure that the repayment chain is the origin chain if the deposit originates
This was the result of a local change not being pushed. This change is now outdated and the new version uses a closer to where the data is updated.

2024-06-24 19:09 UTC, pxrl commented on src/relayer/Relayer.ts
> +        return;
The funds won't be stuck forever since if not filled then they'd just be refunded on the origin chain. I think the most likely scenario here is that a third-party relayer wants to rebalance out of a lite chain (i.e. lite chain back to mainnet). In that scenario it'd be pretty annoying if their own bot kept filling it and requesting payment on the origin chain.

2024-06-24 19:10 UTC, pxrl commented on src/relayer/Relayer.ts
> +      this.logger[this.config.sendingRelaysEnabled ? "warn" : "debug"]({
I don't think this should warn - it'll create a lot of noise out of the main relayer for the duration of the lookback (2 hours).

2024-06-24 19:12 UTC, james-a-morris commented on src/relayer/Relayer.ts
> +    if (deposit.originatesFromLiteChain) {
Agreed - but I'm not sure this is in the scope of this PR

2024-06-24 19:13 UTC, nicholaspai commented on src/utils/FillUtils.ts
> +  originatesFromLiteChain: boolean
nit: prefer naming this `fromLiteChain`

2024-06-24 19:14 UTC, nicholaspai commented on test/Dataworker.loadData.ts
> +      expect(repaymentChainId).to.not.eq(spokePoolClient_1.chainId);
```suggestion
      expect(repaymentChainId).to.not.eq(originChainId);
```

is this more correct for preserving this test's usefulness?

2024-06-24 19:14 UTC, nicholaspai commented on test/Dataworker.loadData.ts
> +      expect(repaymentChainId).to.not.eq(spokePoolClient_1.chainId);
```suggestion
      expect(repaymentChainId).to.not.eq(originChainId);
```

same suggestion as above

2024-06-24 19:15 UTC, nicholaspai reviewed
This looks good! Question is should we wait for https://github.com/across-protocol/sdk/pull/669 also to be incorporated? I also left some nits pls review

2024-06-24 19:19 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +        return;
in either case this filler is going to receive funds on the origin chain i don't understand?

2024-06-24 19:34 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +      this.logger[this.config.sendingRelaysEnabled ? "warn" : "debug"]({
i'm good with that ^

2024-06-24 19:34 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +      this.logger[this.config.sendingRelaysEnabled ? "warn" : "debug"]({
let's change to debug

2024-06-24 19:34 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +    if (deposit.originatesFromLiteChain) {
just a reminder i don't want to forget

2024-06-24 19:51 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +        return;
ok i understand. I think the original implementation where we exit early here is preferable but I didn't understand the original context. Can you add a comment here that we don't want to fast fill any deposit that we send because we should assume that  for these deposits, we would always prefer someone else to fill them since we must take repayment on the origin chain, which would result in a net-no change in capital allocation for our account and force us to pay an LP fee

2024-06-25 14:09 UTC, james-a-morris commented on test/Dataworker.loadData.ts
> +      expect(repaymentChainId).to.not.eq(spokePoolClient_1.chainId);
https://github.com/across-protocol/relayer/pull/1629/commits/a489074b3e00abe73d27929ddb2c69b953ad86b4

2024-06-25 14:10 UTC, james-a-morris commented on test/Dataworker.loadData.ts
> +      expect(repaymentChainId).to.not.eq(spokePoolClient_1.chainId);
https://github.com/across-protocol/relayer/pull/1629/commits/a489074b3e00abe73d27929ddb2c69b953ad86b4

2024-06-25 14:10 UTC, james-a-morris commented on src/utils/FillUtils.ts
> +  originatesFromLiteChain: boolean
https://github.com/across-protocol/relayer/pull/1629/commits/61d5d998dbbb0e5bbe002aedfcf584875f151d2d

2024-06-25 14:18 UTC, james-a-morris commented on src/relayer/Relayer.ts
> +      this.fillRelay(deposit, deposit.originatesFromLiteChain ? deposit.originChainId : destinationChainId, lpFeePct);
https://github.com/across-protocol/relayer/pull/1629/commits/33012fb800780137497b065ad02a59dfa0d20f4d

2024-06-25 14:21 UTC, james-a-morris commented on src/relayer/Relayer.ts
> +        return;
https://github.com/across-protocol/relayer/pull/1629/commits/33012fb800780137497b065ad02a59dfa0d20f4d
https://github.com/across-protocol/relayer/pull/1629/commits/42318f204156d570b66f2df6f130cb0574e70b4e

2024-06-25 16:02 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +                v3RelayHashes[this.getRelayHashFromEvent(fill)].deposit.fromLiteChain
```suggestion
                matchedDeposit.fromLiteChain
```

2024-06-25 16:04 UTC, nicholaspai reviewed
Will review again after we merge in #1635

2024-06-25 22:11 UTC, nicholaspai requested changes

2024-06-25 22:11 UTC, nicholaspai commented on src/clients/InventoryClient.ts
> +      return [originChainId];
I think we can do better than this. I think if the origin chain is a lite chain we can evaluate the origin chain as a possible repayment chain choice. Then go through the usual under or over allocation decision. 

Typically if a chain is under allocated we will proceed with the repayment chain otherwise default to mainnet. 

However for lite chains, we can protect our inventory by NOT defaulting to mainnet and choosing not to fill this deposit if we hit that fallback case. This way we never get our inventory over allocated on a lite chain.

2024-06-26 18:11 UTC, nicholaspai approved these changes
I'd like to see @pxrl review

2024-06-26 18:11 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +    if (deposit.fromLiteChain) {
Should we merge these if statements?

2024-06-28 12:23 UTC, pxrl commented on src/clients/InventoryClient.ts
>        this._l1TokenEnabledForChain(l1Token, Number(destinationChainId))
Minor: The majority of deposits will not originate from a lite chain so I think it makes sense to evaluate this last.

```suggestion
      !chainsToEvaluate.includes(destinationChainId) &&
      this._l1TokenEnabledForChain(l1Token, Number(destinationChainId)) &&
      !deposit.fromLiteChain
```

2024-06-28 12:23 UTC, pxrl commented on src/clients/ProfitClient.ts
> +      toLiteChain: false, // TODO: We *may* care about this in the future.
These don't affect gas consumption so we're OK to drop the comments.

```suggestion
      fromLiteChain: false,
      toLiteChain: false,
```

2024-06-28 12:23 UTC, pxrl commented on src/relayer/Relayer.ts
> +      // in no net change in capital allocation for our account and avoiding the need to pay an LP fee.
I don't think this comment is correct - avoiding self-fills from lite chains will result in the relayer moving its balance from the lite chain to the destination chain.

```suggestion
      // prefer someone else to fill the deposits.
```

2024-06-28 12:23 UTC, pxrl commented on src/relayer/Relayer.ts
> +    if (deposit.fromLiteChain) {
+1 - I think we should optimise compact code on these lite clauses.

2024-06-28 12:23 UTC, pxrl commented on src/relayer/Relayer.ts
> +      `Lite chain deposits must be filled on their origin chain. Deposit ${deposit.depositId}.`
It'd help to identify the origin chain as well, because otherwise there's no context to the deposit ID :+1:

2024-06-28 12:23 UTC, pxrl commented on test/Relayer.UnfilledDeposits.ts
> +      .excludingEvery(["realizedLpFeePct", "quoteBlockNumber", "fromLiteChain", "toLiteChain"])
ooc, why do these fields need to be ignored? They seem to be required per the Deposit type in the SDK, so I'd have expected them to be defined.

2024-06-28 12:28 UTC, pxrl commented on src/clients/BundleDataClient.ts
> +            );
Looking above, I can see that we have already filtered by `hasMatchingDeposit`, so I guess we can probably just `assert(isDefined(matchingDeposit))`. wdyt?

(I think this could probably be refactored later but I don't think it makes sense to do that as part of introducing a new feature)

2024-07-01 11:07 UTC, amateima commented on src/clients/BundleDataClient.ts
> +                  v3RelayHashes[relayDataHash].deposit.toLiteChain
> we're concerned about the slow fill being unexecutable on arrival and needing to be pulled back in a subsequent bundle. Is that the reason for this?

Yes, that's the reason

2024-07-01 12:53 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +              }
Agreed this should never hit

2024-07-01 12:54 UTC, nicholaspai commented on src/clients/InventoryClient.ts
> +   * there is no fallback if the origin chain is not an eligible repayment chain.
It's ineligible if the origin chain is over allocated from an inventory management perspective

2024-07-01 13:45 UTC, james-a-morris commented
@pxrl consolidating comments related to the asserts/throws:

https://github.com/across-protocol/relayer/pull/1629/commits/9857d74d53722a72132722a74ec1c958de784086

2024-07-01 13:56 UTC, james-a-morris commented on src/relayer/Relayer.ts
> +      // in no net change in capital allocation for our account and avoiding the need to pay an LP fee.
Very fair point

2024-07-01 13:58 UTC, james-a-morris commented on test/Relayer.UnfilledDeposits.ts
> +      .excludingEvery(["realizedLpFeePct", "quoteBlockNumber", "fromLiteChain", "toLiteChain"])
They are ignored for the scope of the test. Our harness itself isn't set up to handle these yet, so I figured it was convenient to ignore and test them separately

2024-07-01 14:58 UTC, pxrl approved these changes
LGTM!

2024-07-01 20:03 UTC, merged