feat: disable slow fills for deposits involving lite chains
across-protocol/relayer pull request #1635
Opened 2024-06-21 12:27 UTC by amateima

This PR aims to disable slow fills for deposits that need to be filled on a lite chain or originating from a lite chain.

2024-06-21 12:30 UTC, amateima commented on src/clients/BundleDataClient.ts
> +
Not sure if this logic needs to be placed here or before line 903, case in which the `slowFillRequest` key of object `v3RelayHashes[relayDataHash]` would not be populated at all

2024-06-21 13:03 UTC, james-a-morris commented on src/relayer/Relayer.ts
> +    if (configStoreClient.isChainLiteChainAtTimestamp(deposit.originChainId, deposit.quoteTimestamp)) {
We can directly call `deposit.originatesFromLiteChain` - it's flagged in all `DepositV3` objects that originate from a spoke pool

2024-06-21 13:10 UTC, pxrl commented on src/relayer/Relayer.ts
> +    if (configStoreClient.isChainLiteChainAtTimestamp(deposit.originChainId, deposit.quoteTimestamp)) {
@james-a-morris That also means we'll be pushing `originatesFromLiteChain` to Arweave, right? That'd probably warranty a version bump there, unless we suppress it. I'm not sure whether it's actually useful to have it in Arweave so it might be OK to suppress - wdyt?

2024-06-21 13:44 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +
I think it has to follow 910 at least because there we assert the existence of the `deposit` in `v3RelayHashes[relayDataHash]`

2024-06-21 13:45 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +    if (configStoreClient.isChainLiteChainAtTimestamp(deposit.originChainId, deposit.quoteTimestamp)) {
Can we add a debug log here explaining why we're exiting early?

2024-06-21 13:45 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +      return;
same comment as https://github.com/across-protocol/relayer/pull/1635/files#r1648988787

2024-06-25 11:27 UTC, nicholaspai approved these changes
This looks great but we need to resolve conflicts with #1629

2024-06-25 11:27 UTC, nicholaspai commented on src/relayer/Relayer.ts
> +    if (deposit.fromLiteChain) {
@james-a-morris @amateima what should we do with merge conflicts between your prs? Should this PR into James' ?

2024-06-25 11:49 UTC, amateima commented on src/relayer/Relayer.ts
> +    if (deposit.fromLiteChain) {
I was thinking the same, yes

2024-06-25 14:01 UTC, james-a-morris approved these changes

2024-06-25 16:28 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +                // slow fill requests for deposits originating from a lite chain are considered invalid
We need these same if statements within the if-block at 972

2024-06-25 16:29 UTC, nicholaspai commented on test/Dataworker.loadData.ts
> +    it("Slow fill request for deposit that isn't eligible for slow fill because destination is lite chain", async function () {
We need additional unit tests for slow fill requests where the deposit needs to be fetched from a historical query like https://github.com/across-protocol/relayer/blob/746bda6b77f67e5fe29e32ac41bb0c8b0cde131b/test/Dataworker.loadData.ts#L845

2024-06-25 16:29 UTC, nicholaspai requested changes
We are missing a check in the BundleDataClient where the slow fill request matches with an older deposit

2024-06-26 10:45 UTC, amateima commented on test/Dataworker.loadData.ts
> +    it("Slow fill request for deposit that isn't eligible for slow fill because destination is lite chain", async function () {
good catch

2024-06-26 14:27 UTC, nicholaspai approved these changes
Lgtm but I left some simple nut suggestions

2024-06-26 14:27 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +                if (v3RelayHashes[relayDataHash].deposit.fromLiteChain) {
Should we collapse these two if statements into a single one?

2024-06-26 14:27 UTC, nicholaspai commented on src/clients/BundleDataClient.ts
> +              if (matchedDeposit.fromLiteChain) {
Should we collapse these two if statements?

2024-06-26 14:41 UTC, amateima commented on src/clients/BundleDataClient.ts
> +                if (v3RelayHashes[relayDataHash].deposit.fromLiteChain) {
Yep. Will do!

2024-06-26 14:41 UTC, amateima commented on src/clients/BundleDataClient.ts
> +              if (matchedDeposit.fromLiteChain) {
Yep. Will do!

2024-06-26 14:59 UTC, merged