chore: fix some comments
across-protocol/relayer pull request #1755
Opened 2024-08-16 15:48 UTC by mountdisk

2024-08-16 15:52 UTC, james-a-morris requested changes
two comments.

2024-08-16 15:52 UTC, james-a-morris commented on src/clients/TokenClient.ts
> +  // If the relayer tries to execute a relay but does not have enough tokens to fully fill it will capture the
The original looks correct here. The first `it` is a pronoun reference to the relay. It's a bit vague so maybe we can change that?

2024-08-16 15:52 UTC, james-a-morris commented on src/finalizer/utils/opStack.ts
> +    // @dev The hintId parameter plays a role in our insurance mechanism that kicks in the rare event that
The original was correct here. The first `in` is part of the phrase `kicks in`. I'd recommend maybe we use `kicks-in` instead but I don't think we should remove the second `in`.

2024-08-21 12:33 UTC, pxrl commented
@mountdisk  I don't think these are comments that need to be changed. Happy to consider other PRs if you find anything else.

2024-08-21 12:33 UTC, closed without merging